### ISSUE TITLE
Provide inputs

### ISSUE THREAD

**Issue by prvsousa** [AarhusCrypto/DUPLO#5]
I want to ask you something related to the issue in the TinyLEGO: https://github.com/AarhusCrypto/TinyLEGO/issues/1

I want to know how can I provide the inputs instead of provide them inside the files "somethinginput_0.bin". 

Can you give me some guidance for this? This implementation is a little bit different.

**Comment by RobTrifiletti** [comment]
Hi there!

It should be exactly the same actually. For the respective parties the input arrays are defined at
duplo-const-main.cpp:254
duplo-eval-main.cpp:251

However there was a missing option to use "Bristol" circuits as input on the command line. I just pushed this fix. I have successfully run the string compare circuit described at [AarhusCrypto/TinyLEGO#1](https://github.com/AarhusCrypto/TinyLEGO/issues/1) as follows
./build/release/DuploConstructor -ip localhost -n 1 -f ../TinyLEGO/compare.txt -b 1 & ./build/release/DuploEvaluator -ip localhost -n 1 -f ../TinyLEGO/compare.txt -b 1

In the above assuming that the compare.txt circuit is located at the relative path ../TinyLEGO/compare.txt

Notice the -b flag is used to instruct the code to treat the circuit as bristol format. If not present it will crash as it by default is expecting a circuit in duplo format (as output by the Frigate compiler).

**Comment by prvsousa** [comment]
In the example of TinyLEGO you have something like:
```

 if (!circuit_name.empty()) {
    for (int i = 0; i < circuit.num_const_inp_wires; ++i) {
      const_input[i] = GetBitReversed(i, input_buffer);
    }
  }

```
And I replace this with the fill directly of the const_input. but here I don't get how can you fill the inputs

**Comment by RobTrifiletti** [comment]
In these main files there is no reading input from disk. It is always running the computation on the all-zero input. The below initialises the input to hold composed_circuit.num_const_inp_wires input wires (which is 16 for our circuit) and it sets all these to 0 by default. Since it is never modified it results in running the computation with the all-zero input.

`
osuCrypto::BitVector inputs(composed_circuit.num_const_inp_wires); //0 input
`
Therefore you can in the same way just set it directly, such as inputs[0] = 1, inputs[1] = 0, etc..

You should view the duplo-const-main and duplo-eval-main as example code of how to use and run the underlying duplo code. If included in a larger application one would not use these duplo-xxx-main files, but call the duplo object directly. The main files just show a working example of how to call duplo for a typical use case (however hardcoded to always use the all-zero input).

**Comment by prvsousa** [comment]
Solved.Thanks!
